#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

### COLORS ###
# Set the custom colors from wal.
source "$HOME/.cache/wal/colors.sh"
#bspc config normal_border_color $color0
#bspc config focused_border_color $color1
#bspc config active_border_color $color1
#bspc config urgent_border_color $color7
#bspc config presel_feedback_color $color1

FOREGROUND="$foreground"
BACKGROUND="$background"
BLACK="$color0"
RED="$color1"
GREEN="$color2"
YELLOW="$color3"
BLUE="$color4"
MAGENTA="$color5"
CYAN="$color6"
WHITE="$color7"

#Wallpaper
feh --bg-fill ~/Pictures/background.jpeg

#Polybar
polybar bar &
wal -i $HOME/Pictures/background.jpeg

# Zathura pdf
bspc rule -a Zathura state=tiled
